### ISSUE TITLE
Assets doesn't included to the App

### ISSUE THREAD

**Issue by pocorall** [Darkyenus/roboscala-samples#5]
After `hello/iphoneSim`, the simulator appeared with a textField and the `Hello, world!` label, but the nice earth image(`Background.png`) is not appeared. The app icon is the default one as well, not the red-colored one(`icon.png`).

Is there any problem with resources?

**Comment by Darkyenus** [comment]
I am aware of this, but I haven't yet got time to fix it. (I know that it is a problem with samples and not with the plugin, so it wasn't a priority)
